# 1. Introducing Joins

In the SQL Fundamentals course, we worked exclusively with data that existed in a single table. In the real world, it's much more common for databases to have data in more than one table. If we want to be able to work with that data, we'll have to combine multiple tables within a query. The way we do this in SQL is using joins

The most common way to join data using SQL is using an inner join. The syntax for an inner join is:

`SELECT [column_names] FROM [table_name_one]
INNER JOIN [table_name_two] ON [join_constraint];`

The inner join clause is made up of two parts:

* **INNER JOIN**, which tells the SQL engine the name of the table you wish to join in your query, and that you wish to use an inner join.
* **ON**, which tells the SQL engine what columns to use to join the two tables.

`Joins are usually used in a query after the FROM clause`

## TODO:
* Write a query that returns all columns from the facts and cities tables.
  * Use an INNER JOIN to join the cities table to the facts table.
  * Join the tables on the values where facts.id and cities.facts_id are equal.
  * Limit the query to the first 10 rows.

In [1]:
%load_ext sql

In [2]:
%sql sqlite:///factbook.db

In [3]:
%%sql

SELECT * FROM facts
INNER JOIN cities ON facts.id=cities.facts_id
LIMIT 10;

 * sqlite:///factbook.db
Done.

[(216, 'aa', 'Aruba', 180, 180, 0, 112162, 1.33, 12.56, 8.18, 8.92, 1, 'Oranjestad', 37000, 1, '216'),
 (6, 'ac', 'Antigua and Barbuda', 442, 442, 0, 92436, 1.24, 15.85, 5.69, 2.21, 2, "Saint John'S", 27000, 1, '6'),
 (184, 'ae', 'United Arab Emirates', 83600, 83600, 0, 5779760, 2.58, 15.43, 1.97, 12.36, 3, 'Abu Dhabi', 942000, 1, '184'),
 (184, 'ae', 'United Arab Emirates', 83600, 83600, 0, 5779760, 2.58, 15.43, 1.97, 12.36, 4, 'Dubai', 1978000, 0, '184'),
 (184, 'ae', 'United Arab Emirates', 83600, 83600, 0, 5779760, 2.58, 15.43, 1.97, 12.36, 5, 'Sharjah', 983000, 0, '184'),
 (1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51, 6, 'Kabul', 3097000, 1, '1'),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92, 7, 'Algiers', 2916000, 1, '3'),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92, 8, 'Oran', 783000, 0, '3'),
 (11, 'aj', 'Azerbaijan', 86600, 82629, 3971, 9780780, 0.96, 16.64, 7.07, 0.0, 9, 'Baku', 2123000, 1, '11'),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3, 10, 'Tirana', 419000, 1, '2')]

# 2. Understanding Inner Joins

**An inner join works by including only rows from each table that have a match as specified using the ON clause.**

**`We can also create aliases for table names, which makes queries with joins easier to both read and write.`**

* We can also combine aliases with wildcards - for instance, using the aliases created above, c.* would give us all columns from the table cities

In [4]:
from IPython.display import SVG
SVG(filename='venn_inner.svg')

## TODO:
Write a query that:
* Joins cities to facts using an INNER JOIN.
* Uses aliases for table names.
* Includes, in order:
* All columns from cities.
* The name column from facts aliased to country_name.
* Includes only the first 5 rows.

In [5]:
%%sql

SELECT C.*,f.name AS contry_name
FROM cities AS c
INNER JOIN facts AS f ON c.facts_id=f.id
LIMIT 5;

 * sqlite:///factbook.db
Done.

[(1, 'Oranjestad', 37000, 1, '216', 'Aruba'),
 (2, "Saint John'S", 27000, 1, '6', 'Antigua and Barbuda'),
 (3, 'Abu Dhabi', 942000, 1, '184', 'United Arab Emirates'),
 (4, 'Dubai', 1978000, 0, '184', 'United Arab Emirates'),
 (5, 'Sharjah', 983000, 0, '184', 'United Arab Emirates')]

# 3. Practicing Inner Joins

## TODO:
* Write a query that uses an INNER JOIN to join the two tables in your query and returns, in order:
  * A column of country names, called country.
  * A column of each country's capital city, called capital_city.

In [6]:
%%sql

SELECT f.name country, c.name capital_city FROM cities c
INNER JOIN facts f ON f.id = c.facts_id
WHERE c.capital = 1

 * sqlite:///factbook.db
Done.

[('Aruba', 'Oranjestad'),
 ('Antigua and Barbuda', "Saint John'S"),
 ('United Arab Emirates', 'Abu Dhabi'),
 ('Afghanistan', 'Kabul'),
 ('Algeria', 'Algiers'),
 ('Azerbaijan', 'Baku'),
 ('Albania', 'Tirana'),
 ('Armenia', 'Yerevan'),
 ('Andorra', 'Andorra La Vella'),
 ('Angola', 'Luanda'),
 ('American Samoa', 'Pago Pago'),
 ('Argentina', 'Buenos Aires'),
 ('Australia', 'Canberra'),
 ('Austria', 'Vienna'),
 ('Anguilla', 'The Valley'),
 ('Bahrain', 'Manama'),
 ('Barbados', 'Bridgetown'),
 ('Botswana', 'Gaborone'),
 ('Bermuda', 'Hamilton'),
 ('Belgium', 'Brussels'),
 ('Bahamas, The', 'Nassau'),
 ('Bangladesh', 'Dhaka'),
 ('Belize', 'Belmopan'),
 ('Bosnia and Herzegovina', 'Sarajevo'),
 ('Bolivia', 'La Paz'),
 ('Burma', 'Rangoon'),
 ('Benin', 'Porto-Novo'),
 ('Belarus', 'Minsk'),
 ('Solomon Islands', 'Honiara'),
 ('Brazil', 'Brasilia'),
 ('Bhutan', 'Thimphu'),
 ('Bulgaria', 'Sofia'),
 ('Brunei', 'Bandar Seri Begawan'),
 ('Burundi', 'Bujumbura'),
 ('Canada', 'Ottawa'),
 ('Cambodia', 'Phnom Penh'),
 ('Chad', "N'Djamena"),
 ('Sri Lanka', 'Colombo'),
 ('Congo, Republic of the', 'Brazzaville'),
 ('Congo, Democratic Republic of the', 'Kinshasa'),
 ('China', 'Beijing'),
 ('Chile', 'Santiago'),
 ('Cayman Islands', 'George Town'),
 ('Cameroon', 'Yaounde'),
 ('Comoros', 'Moroni'),
 ('Colombia', 'Bogota'),
 ('Northern Mariana Islands', 'Saipan'),
 ('Costa Rica', 'San Jose'),
 ('Central African Republic', 'Bangui'),
 ('Cuba', 'Havana'),
 ('Cabo Verde', 'Praia'),
 ('Cyprus', 'Nicosia'),
 ('Denmark', 'Copenhagen'),
 ('Djibouti', 'Djibouti'),
 ('Dominica', 'Roseau'),
 ('Dominican Republic', 'Santo Domingo'),
 ('Ecuador', 'Quito'),
 ('Egypt', 'Cairo'),
 ('Ireland', 'Dublin'),
 ('Equatorial Guinea', 'Malabo'),
 ('Estonia', 'Tallinn'),
 ('Eritrea', 'Asmara'),
 ('El Salvador', 'San Salvador'),
 ('Ethiopia', 'Addis Ababa'),
 ('Czech Republic', 'Prague'),
 ('Finland', 'Helsinki'),
 ('Fiji', 'Suva'),
 ('Falkland Islands (Islas Malvinas)', 'Stanley'),
 ('Micronesia, Federated States of', 'Palikir'),
 ('Faroe Islands', 'Torshavn'),
 ('French Polynesia', 'Papeete'),
 ('France', 'Paris'),
 ('Gambia, The', 'Banjul'),
 ('Gabon', 'Libreville'),
 ('Georgia', 'Tbilisi'),
 ('Ghana', 'Accra'),
 ('Grenada', "Saint George'S"),
 ('Greenland', 'Nuuk'),
 ('Germany', 'Berlin'),
 ('Guam', 'Hagatna'),
 ('Greece', 'Athens'),
 ('Guatemala', 'Guatemala City'),
 ('Guinea', 'Conakry'),
 ('Guyana', 'Georgetown'),
 ('Haiti', 'Port-Au-Prince'),
 ('Honduras', 'Tegucigalpa'),
 ('Croatia', 'Zagreb'),
 ('Hungary', 'Budapest'),
 ('Iceland', 'Reykjavik'),
 ('Indonesia', 'Jakarta'),
 ('Isle of Man', 'Douglas'),
 ('India', 'New Delhi'),
 ('Iran', 'Tehran'),
 ('Israel', 'Jerusalem'),
 ('Italy', 'Rome'),
 ("Cote d'Ivoire", 'Yamoussoukro'),
 ('Iraq', 'Baghdad'),
 ('Japan', 'Tokyo'),
 ('Jamaica', 'Kingston'),
 ('Jordan', 'Amman'),
 ('Kenya', 'Nairobi'),
 ('Kyrgyzstan', 'Bishkek'),
 ('Korea, North', 'Pyongyang'),
 ('Kiribati', 'Tarawa'),
 ('Korea, South', 'Seoul'),
 ('Kuwait', 'Kuwait'),
 ('Kazakhstan', 'Astana'),
 ('Laos', 'Vientiane'),
 ('Lebanon', 'Beirut'),
 ('Latvia', 'Riga'),
 ('Lithuania', 'Vilnius'),
 ('Liberia', 'Monrovia'),
 ('Slovakia', 'Bratislava'),
 ('Liechtenstein', 'Vaduz'),
 ('Lesotho', 'Maseru'),
 ('Luxembourg', 'Luxembourg'),
 ('Libya', 'Tripoli'),
 ('Madagascar', 'Antananarivo'),
 ('Moldova', 'Chisinau'),
 ('Mongolia', 'Ulaanbaatar'),
 ('Malawi', 'Lilongwe'),
 ('Montenegro', 'Podgorica'),
 ('Macedonia', 'Skopje'),
 ('Mali', 'Bamako'),
 ('Morocco', 'Rabat'),
 ('Mauritius', 'Port Louis'),
 ('Mauritania', 'Nouakchott'),
 ('Malta', 'Valletta'),
 ('Oman', 'Muscat'),
 ('Maldives', 'Male'),
 ('Mexico', 'Mexico City'),
 ('Malaysia', 'Kuala Lumpur'),
 ('Mozambique', 'Maputo'),
 ('New Caledonia', 'Noumea'),
 ('Niger', 'Niamey'),
 ('Vanuatu', 'Port-Vila'),
 ('Nigeria', 'Abuja'),
 ('Netherlands', 'Amsterdam'),
 ('Norway', 'Oslo'),
 ('Nepal', 'Kathmandu'),
 ('Suriname', 'Paramaribo'),
 ('Nicaragua', 'Managua'),
 ('New Zealand', 'Wellington'),
 ('South Sudan', 'Juba'),
 ('Paraguay', 'Asuncion'),
 ('Peru', 'Lima'),
 ('Pakistan', 'Islamabad'),
 ('Poland', 'Warsaw'),
 ('Panama', 'Panama City'),
 ('Portugal', 'Lisbon'),
 ('Papua New Guinea', 'Port Moresby'),
 ('Palau', 'Melekeok'),
 ('Guinea-Bissau', 'Bissau'),
 ('Qatar', 'Doha'),
 ('Serbia', 'Belgrade'),
 ('Marshall Islands', 'Majuro'),
 ('Romania', 'Bucharest'),
 ('Philippines', 'Manila'),
 ('Puerto Rico', 'San Juan'),
 ('Russia', 'Moscow'),
 ('Rwanda', 'Kigali'),
 ('Saudi Arabia', 'Riyadh'),
 ('Saint Pierre and Miquelon', 'Saint-Pierre'),
 ('Saint Kitts and Nevis', 'Basseterre'),
 ('Seychelles', 'Victoria'),
 ('South Africa', 'Pretoria'),
 ('Senegal', 'Dakar'),
 ('Saint Helena, Ascension, and Tristan da Cunha', 'Jamestown'),
 ('Slovenia', 'Ljubljana'),
 ('Sierra Leone', 'Freetown'),
 ('Somalia', 'Mogadishu'),
 ('Spain', 'Madrid'),
 ('Saint Lucia', 'Castries'),
 ('Sudan', 'Khartoum'),
 ('Sweden', 'Stockholm'),
 ('Syria', 'Damascus'),
 ('Switzerland', 'Bern'),
 ('Trinidad and Tobago', 'Port-Of-Spain'),
 ('Thailand', 'Bangkok'),
 ('Tajikistan', 'Dushanbe'),
 ('Turks and Caicos Islands', 'Grand Turk'),
 ('Togo', 'Lome'),
 ('Sao Tome and Principe', 'Sao Tome'),
 ('Tunisia', 'Tunis'),
 ('Timor-Leste', 'Dili'),
 ('Turkey', 'Ankara'),
 ('Tuvalu', 'Funafuti'),
 ('Turkmenistan', 'Ashgabat'),
 ('Tanzania', 'Dar Es Salaam'),
 ('Uganda', 'Kampala'),
 ('United Kingdom', 'London'),
 ('Ukraine', 'Kyiv'),
 ('United States', 'Washington, D.C.'),
 ('Burkina Faso', 'Ouagadougou'),
 ('Uruguay', 'Montevideo'),
 ('Uzbekistan', 'Tashkent'),
 ('Saint Vincent and the Grenadines', 'Kingstown'),
 ('Venezuela', 'Caracas'),
 ('British Virgin Islands', 'Road Town'),
 ('Vietnam', 'Hanoi'),
 ('Virgin Islands', 'Charlotte Amalie'),
 ('Namibia', 'Windhoek'),
 ('Wallis and Futuna', 'Mata-Utu'),
 ('Samoa', 'Apia'),
 ('Swaziland', 'Mbabane'),
 ('Yemen', 'Sanaa'),
 ('Zambia', 'Lusaka'),
 ('Zimbabwe', 'Harare')]

# 4. Left Joins

## TODO:
Write a query that returns the countries that don't exist in cities:
* Your query should return two columns:
  * The country names, with the alias country.
  * The country population.
* Use a LEFT JOIN to join cities to facts.
* Include only the countries from facts that don't have a corresponding value in cities.

In [7]:
%%sql

SELECT f.name country, f.population
FROM facts f
LEFT JOIN cities c ON c.facts_id = f.id
WHERE c.name IS NULL;

 * sqlite:///factbook.db
Done.

[('Kosovo', 1870981),
 ('Monaco', 30535),
 ('Nauru', 9540),
 ('San Marino', 33020),
 ('Singapore', 5674472),
 ('Holy See (Vatican City)', 842),
 ('Taiwan', 23415126),
 ('European Union', 513949445),
 ('Ashmore and Cartier Islands', None),
 ('Christmas Island', 1530),
 ('Cocos (Keeling) Islands', 596),
 ('Coral Sea Islands', None),
 ('Heard Island and McDonald Islands', None),
 ('Norfolk Island', 2210),
 ('Hong Kong', 7141106),
 ('Macau', 592731),
 ('Clipperton Island', None),
 ('French Southern and Antarctic Lands', None),
 ('Saint Barthelemy', 7237),
 ('Saint Martin', 31754),
 ('Curacao', 148406),
 ('Sint Maarten', 39689),
 ('Cook Islands', 9838),
 ('Niue', 1190),
 ('Tokelau', 1337),
 ('Bouvet Island', None),
 ('Jan Mayen', None),
 ('Svalbard', 1872),
 ('Akrotiri', 15700),
 ('British Indian Ocean Territory', None),
 ('Dhekelia', 15700),
 ('Gibraltar', 29258),
 ('Guernsey', 66080),
 ('Jersey', 97294),
 ('Montserrat', 5241),
 ('Pitcairn Islands', 48),
 ('South Georgia and South Sandwich Islands', None),
 ('Navassa Island', None),
 ('Wake Island', None),
 ('United States Pacific Island Wildlife Refuges', None),
 ('Antarctica', 0),
 ('Gaza Strip', 1869055),
 ('Paracel Islands', None),
 ('Spratly Islands', None),
 ('West Bank', 2785366),
 ('Arctic Ocean', None),
 ('Atlantic Ocean', None),
 ('Indian Ocean', None),
 ('Pacific Ocean', None),
 ('Southern Ocean', None),
 ('World', 7256490011)]

# 5. Right Joins and Outer Joins

`There are two less-common join types SQLite does not support that you should be aware of. The first is a right join. A right join, as the name indicates, is exactly the opposite of a left join. While the left join includes all rows in the table before the JOIN clause, the right join includes all rows in the new table in the JOIN clause.`

`The other join type not supported by SQLite is a full outer join. A full outer join will include all rows from the tables on both sides of the join. We can see a full outer join in the Venn diagram below:`

# 6. Finding the Most Populous Capital Cities

## TODO:
Write a query that returns the 10 capital cities with the highest population ranked from biggest to smallest population.
* You should include the following columns, in order:
  *  capital_city, the name of the city.
  * country, the name of the country the city is from.
  * population, the population of the city.

In [8]:
%%sql

SELECT c.name capital_city, f.name country, c.population
FROM facts f
INNER JOIN cities c ON c.facts_id = f.id
WHERE c.capital = 1
ORDER BY 3 DESC
LIMIT 10;

 * sqlite:///factbook.db
Done.

[('Tokyo', 'Japan', 37217000),
 ('New Delhi', 'India', 22654000),
 ('Mexico City', 'Mexico', 20446000),
 ('Beijing', 'China', 15594000),
 ('Dhaka', 'Bangladesh', 15391000),
 ('Buenos Aires', 'Argentina', 13528000),
 ('Manila', 'Philippines', 11862000),
 ('Moscow', 'Russia', 11621000),
 ('Cairo', 'Egypt', 11169000),
 ('Jakarta', 'Indonesia', 9769000)]

# 7. Combining Joins with Subqueries

## TODO:
Using a join and a subquery, write a query that returns capital cities with populations of over 10 million ordered from largest to smallest. Include the following columns:
  * capital_city - the name of the city.
  * country - the name of the country the city is the capital of.
  * population - the population of the city.

In [9]:
%%sql

SELECT c.name capital_city, f.name country, c.population population
FROM facts f
INNER JOIN (
            SELECT * FROM cities
            WHERE capital = 1
            AND population > 10000000
           ) c ON c.facts_id = f.id
ORDER BY 3 DESC;

 * sqlite:///factbook.db
Done.

[('Tokyo', 'Japan', 37217000),
 ('New Delhi', 'India', 22654000),
 ('Mexico City', 'Mexico', 20446000),
 ('Beijing', 'China', 15594000),
 ('Dhaka', 'Bangladesh', 15391000),
 ('Buenos Aires', 'Argentina', 13528000),
 ('Manila', 'Philippines', 11862000),
 ('Moscow', 'Russia', 11621000),
 ('Cairo', 'Egypt', 11169000)]

# 8. Challenge: Complex Query with Joins and Subqueries

**When you're writing complex queries with joins and subqueries, it helps to follow this process:**

* Think about what data you need in your final output
* Work out which tables you'll need to join, and whether you will need to join to a subquery.
  * If you need to join to a subquery, write the subquery first.
* Then start writing your SELECT clause, followed by the join and any other clauses you will need.
* Don't be afraid to write your query in steps, running it as you go— for instance you can run your subquery as a 'stand alone' query first to make sure it looks like you want before writing the outer query.

## TODO:
Write a query that generates output as shown above. The query should include:
* The following columns, in order:
  * country, the name of the country.
  * urban_pop, the sum of the population in major urban areas belonging to that country.
  * total_pop, the total population of the country.
  * urban_pct, the percentage of the popularion within urban areas, calculated by dividing urban_pop by total_pop.
* Only countries that have an urban_pct greater than 0.5.
* Rows should be sorted by urban_pct in ascending order.

In [10]:
%%sql

SELECT
    f.name country,
    c.urban_pop,
    f.population total_pop,
    (c.urban_pop / CAST(f.population AS FLOAT)) urban_pct
FROM facts f
INNER JOIN (
            SELECT
                facts_id,
                SUM(population) urban_pop
            FROM cities
            GROUP BY 1
           ) c ON c.facts_id = f.id
WHERE urban_pct > .5
ORDER BY 4 ASC;

 * sqlite:///factbook.db
Done.

[('Uruguay', 1672000, 3341893, 0.5003152404939356),
 ('Congo, Republic of the', 2445000, 4755097, 0.5141850944365594),
 ('Brunei', 241000, 429646, 0.5609269026128487),
 ('New Caledonia', 157000, 271615, 0.5780240413821034),
 ('Virgin Islands', 60000, 103574, 0.5792959623071428),
 ('Falkland Islands (Islas Malvinas)', 2000, 3361, 0.5950609937518596),
 ('Djibouti', 496000, 828324, 0.5987995035758954),
 ('Australia', 13789000, 22751014, 0.6060828761302683),
 ('Iceland', 206000, 331918, 0.6206352171319423),
 ('Israel', 5226000, 8049314, 0.6492478737939655),
 ('United Arab Emirates', 3903000, 5779760, 0.6752875551926032),
 ('Puerto Rico', 2475000, 3598357, 0.6878139106264332),
 ('Bahamas, The', 254000, 324597, 0.7825087724162577),
 ('Kuwait', 2406000, 2788534, 0.8628189579183901),
 ('Saint Pierre and Miquelon', 5000, 5657, 0.8838607035531201),
 ('Guam', 169000, 161785, 1.0445962233828847),
 ('Northern Mariana Islands', 56000, 52344, 1.0698456365581537),
 ('American Samoa', 64000, 54343, 1.1777045801667188)]

In this mission we learned:

The difference between inner and left joins.
How to choose which join is appropriate for your task.
Using joins with subqueries, aggregate functions and other SQL techniques.